target:
  # =====================
  # 当前生成章节
  # =====================
  latest_chapter_id: 1

  # =====================
  # 当前剧情定位
  # =====================
  volume: volume_01
  arc: arc_01
  plot: plot_01_01_01
  chapter: chapter0002
  md_file: plot_01_01_01.md

# =====================
# 输出
# =====================
output:
  directory: z_ai_output_drafts
